# Generated by Django 4.2.6 on 2023-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activitydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=20, null=True)),
                ('activityimage', models.ImageField(blank=True, null=True, upload_to='activityimage')),
            ],
        ),
    ]
