# Generated by Django 4.2.6 on 2023-11-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_activitydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(blank=True, max_length=20, null=True)),
                ('roomtype', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('food', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='roomimage')),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
