# Generated by Django 4.2.6 on 2023-11-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_roomdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdb',
            old_name='roomtype',
            new_name='nights',
        ),
    ]
