# Generated by Django 4.2.6 on 2023-11-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_resortdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdb',
            name='food',
        ),
    ]
