# Generated by Django 4.2.6 on 2023-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_roomdb_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
