# Generated by Django 4.2.6 on 2023-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_activitydb_hour_activitydb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydb',
            name='hour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
