# Generated by Django 4.2.6 on 2023-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_activitydb_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedb',
            name='description',
        ),
        migrations.AddField(
            model_name='roomdb',
            name='Hotelimage',
            field=models.ImageField(blank=True, null=True, upload_to='hotelimage'),
        ),
    ]
