# Generated by Django 4.2.6 on 2023-11-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_placedb_description_roomdb_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdb',
            name='Hotelimage',
        ),
    ]
