# Generated by Django 4.2.6 on 2023-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_roomdb_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdb',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roomdb',
            name='roomimage',
            field=models.ImageField(blank=True, null=True, upload_to='roomsimage'),
        ),
    ]
