# Generated by Django 4.2.6 on 2023-11-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_roomdb_description_roomdb_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdb',
            name='roomimage',
        ),
        migrations.AlterField(
            model_name='roomdb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
