# Generated by Django 4.2.6 on 2023-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_contactdb_remove_rating_hotel_delete_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
