# Generated by Django 4.2.6 on 2023-11-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_contactdb_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
