# Generated by Django 4.2.6 on 2023-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_spadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='spadb',
            name='idimage',
            field=models.ImageField(blank=True, null=True, upload_to='id'),
        ),
        migrations.AddField(
            model_name='spadb',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
