# Generated by Django 4.2.6 on 2023-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_remove_spadb_idimage_spadb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelbookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idimage2')),
                ('room', models.IntegerField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
