# Generated by Django 4.2.6 on 2023-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_hotelbookdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='flightdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyfrom', models.CharField(blank=True, max_length=100, null=True)),
                ('flyto', models.CharField(blank=True, max_length=100, null=True)),
                ('departing', models.DateField(blank=True, null=True)),
                ('returning', models.DateField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('travel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
