# Generated by Django 4.2.6 on 2023-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_flightdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_detailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(blank=True, max_length=100, null=True)),
                ('activityprice', models.IntegerField(blank=True, null=True)),
                ('hotelname', models.CharField(blank=True, max_length=100, null=True)),
                ('hotelprice', models.IntegerField(blank=True, null=True)),
                ('hotelnight', models.IntegerField(blank=True, null=True)),
                ('spaname', models.CharField(blank=True, max_length=100, null=True)),
                ('spaprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
