# Generated by Django 4.2.6 on 2023-12-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_booking_detailsdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_detailsdb',
            name='hotelnight',
        ),
    ]
