# Generated by Django 4.2.6 on 2023-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_booking_detailsdb_hotelnight'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details_hoteldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(blank=True, max_length=100, null=True)),
                ('hotelprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking_detailsdb',
            name='hotelname',
        ),
        migrations.RemoveField(
            model_name='booking_detailsdb',
            name='hotelprice',
        ),
        migrations.RemoveField(
            model_name='booking_detailsdb',
            name='spaname',
        ),
        migrations.RemoveField(
            model_name='booking_detailsdb',
            name='spaprice',
        ),
    ]
