# Generated by Django 4.2.6 on 2023-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_booking_details_spadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details_hoteldb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_details_spadb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_detailsdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
