# Generated by Django 4.2.6 on 2023-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_rename_month_paymentdb_monthyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='monthyear',
            field=models.DateField(blank=True, null=True),
        ),
    ]
