# Generated by Django 4.2.6 on 2023-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_alter_paymentdb_monthyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
