# Generated by Django 4.2.6 on 2023-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_paymentdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='spadb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
