# Generated by Django 4.2.6 on 2023-12-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_hotelbookdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp1', models.IntegerField(blank=True, null=True)),
                ('otp2', models.IntegerField(blank=True, null=True)),
                ('otp3', models.IntegerField(blank=True, null=True)),
                ('otp4', models.IntegerField(blank=True, null=True)),
                ('otp5', models.IntegerField(blank=True, null=True)),
                ('otp6', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
