# Generated by Django 4.2.6 on 2023-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verify',
            name='otp2',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='otp3',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='otp4',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='otp5',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='otp6',
        ),
    ]
